keys:
  - &users
    - &tux age14vktfes95f33vuefwnmuvryas7az04u76dsgyhfvsx73czkvmp2q7njkl4

  - &hosts
    - &sirius age15d06qpn64p3w57l8yhdesdr5g69dtncwq8yrkx2uw0szql3p7fsq4awlka
    - &canopus age1udt3cssu7ahdrhsvckt8450rswrr6mknn36xpq74dkfp9lpajvnq84kdzj
    - &homelab age1jg642q775gmnmxeu29gcf3lph8vem4xr8t84cxe809dpd0myrussh49h60
    - &arcturus age1zsl5d4vj6gl3h96y5p53sq5y4vr4vtlwp727h7rp9a4xfkxm53lqrh6r50
    - &alpha age145uq9emlxqzm3wqauy9zqj78wqx9e6h09xag6wust7jjgn4upfzsaemcvx
    - &vega age1ydkclhk9kwqdq74utesqdfupt43lz64d5k65gz2z9uyljcqq9fcq3hv28l
    - &capella age1y4luzn2jls7rvgphej23srvdlx563lxq29tvf66vhwwzaf7c3f3qzvresh

creation_rules:
  - path_regex: hosts/common/secrets.yaml$
    key_groups:
      - age:
          - *tux
          - *sirius
          - *canopus
          - *homelab
          - *arcturus
          - *alpha
          - *vega
          - *capella
  - path_regex: hosts/sirius/secrets.yaml$
    key_groups:
      - age:
          - *tux
          - *sirius
  - path_regex: hosts/canopus/secrets.yaml$
    key_groups:
      - age:
          - *tux
          - *canopus
  - path_regex: hosts/arcturus/secrets.yaml$
    key_groups:
      - age:
          - *tux
          - *arcturus
  - path_regex: hosts/alpha/secrets.yaml$
    key_groups:
      - age:
          - *tux
          - *alpha
